# Generated by Django 3.2.11 on 2022-01-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.product')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='subscription', to='onlinestore.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='product_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.product'),
        ),
    ]
